name: eShopOnWeb Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
    
  sonar_scanner:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code for scanning
        uses: actions/checkout@v2
      - name: Analyze with Sonar Cloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN:  ${{ secrets.SONAR_TOKEN }}
